"""
Test case generator for WAF policies.
Generates curl-based test scripts and test documentation.
"""

import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional


class TestGenerator:
    """Generates test cases from WAF policy configuration."""

    def __init__(self, config: Dict[str, Any], debug: bool = False):
        self.config = config
        self.debug = debug
        self.metadata = config.get("metadata", {})
        self.test_defs = config.get("test_definitions", {})
        self.project = self.metadata.get("project", "waf-policy")

    def generate(self, output_dir: str) -> None:
        """Generate all test files."""
        tests_dir = Path(output_dir) / self.project / "tests"
        tests_dir.mkdir(parents=True, exist_ok=True)

        self._log(f"Generating test files in {tests_dir}")

        self._generate_test_cases_yaml(tests_dir)
        self._generate_test_runner_sh(tests_dir)
        self._generate_test_report_md(tests_dir)

        self._log("Test generation complete!")

    def _log(self, message: str) -> None:
        """Print debug message if debug mode enabled."""
        if self.debug:
            print(f"[DEBUG] {message}")

    def _generate_test_cases_yaml(self, output_dir: Path) -> None:
        """Generate test_cases.yaml file."""
        import yaml

        test_suites = self.test_defs.get("test_suites", [])
        settings = self.test_defs.get("settings", {})

        output = {
            "version": "1.0",
            "metadata": {
                "project": self.project,
                "policy_name": self.metadata.get("policy_name", ""),
                "generated": True
            },
            "settings": settings,
            "test_suites": test_suites
        }

        with open(output_dir / "test_cases.yaml", "w") as f:
            yaml.dump(output, f, default_flow_style=False, sort_keys=False)

    def _generate_test_runner_sh(self, output_dir: Path) -> None:
        """Generate test_runner.sh executable script."""
        settings = self.test_defs.get("settings", {})
        base_url = settings.get("base_url", "https://example.com")
        default_host = settings.get("default_host", "")
        test_data_dir = settings.get("test_data_dir", "./test_data")

        test_suites = self.test_defs.get("test_suites", [])

        # Build test commands
        test_commands = []
        for suite in test_suites:
            suite_name = suite.get("name", "")
            suite_desc = suite.get("description", "")

            test_commands.append(f'''
# ============================================
# Suite: {suite_name}
# {suite_desc}
# ============================================
''')

            tests = suite.get("tests", [])
            for test in tests:
                test_cmd = self._build_curl_command(test, base_url, default_host, test_data_dir)
                test_commands.append(test_cmd)

        all_tests = "\n".join(test_commands)

        content = f'''#!/bin/bash
# WAF Acceptance Test Runner
# Policy: {self.metadata.get("policy_name", self.project)}
# Generated by WAF Policy Generator

set -e

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

# Configuration
BASE_URL="${{BASE_URL:-{base_url}}}"
VERBOSE="${{VERBOSE:-0}}"
TEST_DATA_DIR="${{TEST_DATA_DIR:-{test_data_dir}}}"

# Counters
PASSED=0
FAILED=0
SKIPPED=0

# Functions
log_info() {{
    echo -e "${{BLUE}}[INFO]${{NC}} $1"
}}

log_pass() {{
    echo -e "${{GREEN}}[PASS]${{NC}} $1"
    ((PASSED++))
}}

log_fail() {{
    echo -e "${{RED}}[FAIL]${{NC}} $1"
    ((FAILED++))
}}

log_skip() {{
    echo -e "${{YELLOW}}[SKIP]${{NC}} $1"
    ((SKIPPED++))
}}

run_test() {{
    local test_id="$1"
    local test_name="$2"
    local expected_status="$3"
    shift 3
    local curl_args=("$@")

    echo -n "Testing $test_id ($test_name)... "

    if [ "$VERBOSE" == "1" ]; then
        echo ""
        echo "curl ${{curl_args[@]}}"
    fi

    RESPONSE=$(curl -s -o /dev/null -w "%{{http_code}}" "${{curl_args[@]}}" 2>/dev/null || echo "000")

    if [ "$RESPONSE" == "$expected_status" ]; then
        log_pass "Expected: $expected_status, Got: $RESPONSE"
        return 0
    else
        log_fail "Expected: $expected_status, Got: $RESPONSE"
        return 1
    fi
}}

generate_large_string() {{
    local char="$1"
    local count="$2"
    printf '%*s' "$count" | tr ' ' "$char"
}}

# Header
echo "=========================================="
echo "WAF Acceptance Test Suite"
echo "Policy: {self.metadata.get("policy_name", self.project)}"
echo "Target: $BASE_URL"
echo "=========================================="
echo ""

{all_tests}

# Summary
echo ""
echo "=========================================="
echo "Test Results Summary"
echo "=========================================="
echo -e "Passed:  ${{GREEN}}$PASSED${{NC}}"
echo -e "Failed:  ${{RED}}$FAILED${{NC}}"
echo -e "Skipped: ${{YELLOW}}$SKIPPED${{NC}}"
echo "=========================================="

if [ $FAILED -gt 0 ]; then
    exit 1
else
    exit 0
fi
'''
        script_path = output_dir / "test_runner.sh"
        script_path.write_text(content)
        os.chmod(script_path, 0o755)

    def _build_curl_command(self, test: Dict[str, Any], base_url: str,
                           default_host: str, test_data_dir: str) -> str:
        """Build a curl command for a test case."""
        test_id = test.get("id", "unknown")
        test_name = test.get("name", "")
        test_type = test.get("type", "")
        expected_status = test.get("expected_status", 200)
        request = test.get("request", {})

        method = request.get("method", "GET")
        uri = request.get("uri", "/")
        query_string = request.get("query_string", "")
        headers = request.get("headers", {})
        body = request.get("body", "")
        body_file = request.get("body_file", "")

        # Build URL
        url = f"$BASE_URL{uri}"
        if query_string:
            url += f"?{query_string}"

        # Build curl args
        curl_args = [f'-X {method}']

        for header_name, header_value in headers.items():
            # Handle special generated values
            if header_value.startswith("${GENERATE:"):
                # Extract pattern like ${GENERATE:B*8300}
                match = re.match(r'\$\{GENERATE:(.)\*(\d+)\}', header_value)
                if match:
                    char = match.group(1)
                    count = match.group(2)
                    curl_args.append(f'-H "{header_name}: $(generate_large_string \\"{char}\\" {count})"')
                    continue

            curl_args.append(f'-H "{header_name}: {header_value}"')

        if body:
            curl_args.append(f"-d '{body}'")
        elif body_file:
            curl_args.append(f'-d @"$TEST_DATA_DIR/{body_file}"')

        curl_args.append(f'"{url}"')

        curl_str = " \\\n    ".join(curl_args)

        return f'''
# Test: {test_id}
# Type: {test_type}
# {test_name}
run_test "{test_id}" "{test_name}" "{expected_status}" \\
    {curl_str}
'''

    def _generate_test_report_md(self, output_dir: Path) -> None:
        """Generate test_report.md documentation."""
        test_suites = self.test_defs.get("test_suites", [])

        suite_docs = []
        for suite in test_suites:
            suite_name = suite.get("name", "")
            suite_desc = suite.get("description", "")

            tests_md = []
            tests = suite.get("tests", [])
            for test in tests:
                test_id = test.get("id", "")
                test_name = test.get("name", "")
                test_type = test.get("type", "")
                expected_status = test.get("expected_status", 200)
                request = test.get("request", {})
                description = test.get("description", "")

                method = request.get("method", "GET")
                uri = request.get("uri", "/")

                tests_md.append(f'''
#### {test_id}: {test_name}

| Property | Value |
|----------|-------|
| Type | `{test_type}` |
| Method | `{method}` |
| URI | `{uri}` |
| Expected Status | `{expected_status}` |

{description if description else ""}
''')

            suite_docs.append(f'''
## {suite_name}

{suite_desc}

{"".join(tests_md)}
''')

        content = f'''# WAF Test Report

**Policy:** {self.metadata.get("policy_name", self.project)}
**Version:** {self.metadata.get("policy_version", "1.0")}
**Environment:** {self.metadata.get("environment", "production")}

---

## Overview

This document describes the test cases for validating the WAF policy configuration.

### Test Types

| Type | Description |
|------|-------------|
| `true_positive` | Malicious requests that SHOULD be blocked |
| `false_positive` | Legitimate requests that SHOULD be allowed |
| `boundary` | Edge cases testing rule boundaries |
| `gamified` | Attack attempts with exception parameters |

---

{"".join(suite_docs)}

---

## Running Tests

```bash
# Run all tests
./test_runner.sh

# Run with custom base URL
BASE_URL=https://your-domain.com ./test_runner.sh

# Run with verbose output
VERBOSE=1 ./test_runner.sh
```

## Interpreting Results

- **PASS**: Request received expected HTTP status code
- **FAIL**: Request received unexpected HTTP status code
- **SKIP**: Test was skipped (e.g., missing test data file)

For true_positive tests, we expect 403 (blocked).
For false_positive tests, we expect 200 (allowed).
'''
        (output_dir / "test_report.md").write_text(content)
